language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
script: python test.py
before_script:
- ls ~/.ssh
- cat ~/.ssh/*.pub
before_install:
- openssl aes-256-cbc -K $encrypted_89d77c12114e_key -iv $encrypted_89d77c12114e_iv
  -in id_rsa.enc -out id_rsa -d
